### PR TITLE
Working

### PR DESCRIPTION
**Pull request by BSGreaves**
Content's not the best but that will be improved with time.
I'd like to add a sticky header and footer and had little success. If you have a link to a technique you know works...
Thanks!

### CODE REVIEW

**Comment by morecallan** [comment]
@BSGreaves  FABULOUS. Looks great. Let's talk Saturday about this sticky nav/footers. 

One small change: "Article element with two sections for future projects (placeholders)" ... take this literally.

**Comment by BSGreaves** [comment]
@morecallan Thanks. I see my mistake - easy fix.

Btw all my exercises except for music history are merged.

**Comment by morecallan** [comment]
@BSGreaves Awesome! Looks like we'll have to be giving you a few challenges this weekend :) Get that one commit up and we'll be ready to merge this bad boy.

**Comment by BSGreaves** [comment]
@morecallan A little better? I reduced it to one article with two sections (divs) for future content. And left the placeholder content in there. I'm happy to remove it if that's also a problem. I just wanted to keep the footer on the bottom of the page! Thx.

**Comment by morecallan** [comment]
👍 mergin it!

**Pull request merged**
